security:
    encoders: #quais passwords ele vai ter que gerenciar
        Symfony\Component\Security\Core\User\User: plaintext
        Custom\CMSBundle\Entity\Person: bcrypt
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER] #indica a hierarquia de acesso
    providers:
        chain_providers:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    admin:
                        password: adminpass
                        roles: ROLE_ADMIN
        user_db:
            entity: { class: CMSBundle:Person, property: username }
    firewalls:
        main:
            pattern: /.*
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: cms_person_new
            logout:
                path: /logout
                target: /
            security: true
            anonymous: true
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /cms/person, roles: ROLE_ADMIN }

