cms_person_index:
    path:     /
    defaults: { _controller: "CMSBundle:Person:index" }
    methods:  GET

cms_person_show:
    path:     /{id}/show
    defaults: { _controller: "CMSBundle:Person:show" }
    methods:  GET

cms_person_new:
    path:     /new
    defaults: { _controller: "CMSBundle:Person:new" }
    methods:  [GET, POST]

cms_person_edit:
    path:     /{id}/edit
    defaults: { _controller: "CMSBundle:Person:edit" }
    methods:  [GET, POST]

cms_person_delete:
    path:     /{id}/delete
    defaults: { _controller: "CMSBundle:Person:delete" }
    methods:  DELETE
